application: mgh-rrt
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /show
  script: app.app
  login: required

- url: /
  script: app.app

- url: /addwhohash
  script: app.app

- url: /who/.*
  script: app.app
  #login: required

- url: /index.html
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /img
  static_dir: static/img

libraries:
- name: jinja2
  version: latest

- name: ssl
  version: latest
